---

poller:
   # If true, the script won't exit and will instead poll in
   # an infinite loop
   persist: false
   # Interval in seconds between polls
   interval: 20


# List tapo devices
tapo:
    # Tapo devices require that you log in with the credentials
    # that you use to log into the app
    #
    user: "me@mymail.com"
    passw: "mysecretpass"
    devices:
        - 
            name: "washing-machine"
            ip : 192.168.3.152
        
        - 
            name: "big-fridge"
            ip : 192.168.3.153
    
# List kasa devices
kasa:
    devices:
        - 
            name: "Server"
            ip: 192.168.3.251
        
        - 
            name: "tumble-dryer"
            ip : 192.168.3.151


# InfluxDB outputs
influxdb:
    -
        name: "Cloud"
        url: "https://foo.example.com"
        token: "aaabbbccc=="
        org: "my org"
        bucket: "telegraf"
        
    - 
        name: "local"
        url: "http://192.168.1.10:8086"
        token: "aaabbbccc=="
        org: "my org"
        bucket: "kasa"
        
